FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

# Install additional packages
RUN pip install --upgrade pip
RUN pip install jupyterlab numpy pandas matplotlib scikit-learn

# Set up Jupyter
EXPOSE 8888
